---
title: "Longitudinal predictors of mortality inequalities in Aotearoa New Zealand"
subtitle: "Supervised by Barry Milne with Thomas Lumley, Chris Wild and Alan Lee"
author: "Elizabeth (Liza) Lillian Bolton"
date: "2023-10-12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: slides_lb.css
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      ratio: '16:9'
---
class: inverse

```{r setup, echo=FALSE, message=F}
library(xaringanExtra)


# Set up easy-copy code w.Xaringan extra
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clipboard\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
  ),
  rmarkdown::html_dependency_font_awesome()
)


# Start GIFs at the beginning
xaringanExtra::use_freezeframe()

# Panels
xaringanExtra::use_panelset()

# Tileview
xaringanExtra::use_tile_view()

```

## Motivation

---
## Outline


---
## Literature


---
## Objectives

Use repeated measures over time to better understand the association between SEP and mortality. Specifically:
1.	To test support for .highlight[life-course hypotheses]—*accumulation*, *sensitive period*, and *mobility*—for multiple SEP indicators. 
2.	To assess the extent to which more/harsher experiences of deprivation over time .highlight[explain mortality inequalities] between the two largest ethnic groups, European settlers and Indigenous Māori.
3.	To test whether .highlight[religious affiliation], as an indicator of social/cultural capital, protects against low SEP.



---
## Data

The New Zealand Longitudinal Census links the 1981, 1986, 1991, 1996, 2001 and 2006 New Zealand Censuses of Population and Dwellings. The New Zealand Census-Mortality Study links mortality records to these censuses.

<div class="emphasis-box">
<h3> Tatauranga Aotearoa | Stats New Zealand Data Disclaimer </h3>
<small>
<p>Access to the data used in this study was provided by Statistics New Zealand under conditions designed to give effect to the security and confidentiality provisions of the Statistics Act 2022. The results presented in this study are the work of the author, not Statistics New Zealand.</p>

<p>These results are not official statistics. They have been created for research purposes from the New Zealand Longitudinal Census and New Zealand Census Mortality-Study which are carefully managed by Stats NZ. For more information about Stats NZ’s integrated data please visit https://www.stats.govt.nz/integrated-data/. <p></small>
</div>

---
## Data

### 2006 is the latest census used, but there have been 3 censuses since then

- 2023 data not available yet
- 2018 data has had severe quality issues
- 2011 Census was delayed to 2013 due to earthquakes making linkage to 2006 difficult (Kang, 2017)

The delay of the planned 2011 census due to the Christchurch earthquakes posed challenges for linkage between the census eventually held in 2013 and the 2006 census (Kang, 2017). This will likely place ongoing limitations on research of this nature, but as infrastructure for linked data in Aotearoa develops,  censuses may become just one of many valuable sources for life-course SEP data about New Zealanders. 

---
## Data
### Missing data


---
## Trajectories

<div class="emphasis-box">
Lower SEP is consistently significantly associated with higher mortality. However, most of the life-course hypothesis and SEP indicator combinations across adulthood I tested do not improve classification of mortality outcomes. Where they do, measures of SEP at a single point directly before mortality follow-up are sufficient.
</div>

Scope: Could other methods of comparing models be useful for comparing 

Not a survival model that takes into account as we needed data at the three specified time points. This likely means there is a level of survival bias, so interpretations are for people alive at these three periods. 


---
## Mediation

---
## Religion


Not something to intervene on, but may be an important thing to prepare for. As with many metrics, it is plausible that for 

.highlight[13%] of Pacific People (general census population, all ages) in 2006 reported having no religion while .highlight[23%] reported the same in the 2018 Census.


.footnote[*Ethnic group (detailed total response - level 3) and religious affiliation (total responses) by sex, for the census usually resident population count, 2006, 2013, and 2018 Censuses (RC, TA, SA2, DHB)*. Retrieved from nzdotstat.stats.govt.nz.]

---
## Conclusions



---
# Discussion

---
## Do we stop investing in longitudinal studies?

No! While there is not a strong case for needing repeated measures of official statistics based SEP across adulthood to predict mortality, my thesis did not consider childhood SEP nor other outcomes.  

Future directions: I hope this helps simplify some analyses for researchers to enable these other interesting and important pathways to be pursued.

---
## How does this body of work help inform what governments should invest in to reduce inequalities in mortality?

???
<p1>
Where I am absolutely fine with not being the first to find that poverty is associated with mortality, I am glad to be part of the chorus of voices
</p1>

---
## Limitations


---
## Implications


---
class: inverse, middle, center

# Thank you!

# <a href = "https://www.linkedin.com/in/lizabolton/"><i class="fa-brands fa-linkedin"></i></a>  &nbsp;  &nbsp; <a href="https://github.com/elb0/"><i class="fa-brands fa-square-github"></i></a>

# These slides: [link.lizabolton.com/defense](http://link.lizabolton.com/defense)

---
## References

Kang, I. (2017). New Zealand Longitudinal Census development. *International Journal of Population Data Science*, 1(1). https://doi.org/10.23889/ijpds.v1i1.252



